### PR TITLE
added underscore to request.svgTag regex

### PR DESCRIPTION
**Pull request by LordPachelbel**
If an SVG file has an underscore character anywhere in its `<svg>` tag — e.g. `id="Layer_1"` — then one of the regexes in this plugin's `$.ajax()` callback returns false, and that prevents the SVG file from being inlined.

So I added `_` to that regex.

### CODE REVIEW

**Comment by LordPachelbel** [comment]
My change did some strange things, though. (I think so, anyway.) So I'm cancelling this.

**Comment by tiagoporto** [comment]
@LordPachelbel Could you tell me what happened? Maybe I can think in another solution.

**Comment by LordPachelbel** [comment]
When `svgToInline()` was called the resulting HTML would be a messed-up `<svg>` tag. I see now that my later commits put the `_` in the wrong part of the regex, and it's possible our npm-grunt-bower build process ended up using the broken regex code. (I made those other commits because I didn't want to rebuild the project.)

Original regex:
`request.svgTag = request.element.match(/<svg[\w\s\t\n:="\\'\/.#-]+>/g);`

What I intended to do, and did correctly in the initial patch branch:
`request.svgTag = request.element.match(/<svg[\w\s\t\n:="\\'\/.#-_]+>/g);`

What I accidentally did in the other commits:
`request.svgTag = request.element.match(/<svg[\w\s\t\n:="\\'\/.#-]+_>/g);`

So maybe my original patch actually works fine.

**Comment by LordPachelbel** [comment]
(Sorry that I deleted the repo with my code in it!)

**Pull request closed without merging**
